### ISSUE TITLE
网站已重定向至真正的色情网站

### ISSUE THREAD

**Issue by niangaonb** [arcxingye/arcxingye.github.io#6]
我向浏览器内键入链接：“avcxingye.hithub.io/r18/index.html”。然而显示的并不是您编写的网页，而是重定向是真正的色情网站，可以麻烦您处理一下这件事情吗？这样也许会帮到很多人。
![1](https://github.com/arcxingye/arcxingye.github.io/assets/93063977/595b3d7d-1a56-45f8-8519-5c47e04116f5)
![2](https://github.com/arcxingye/arcxingye.github.io/assets/93063977/e5dd7094-3289-4bbc-995f-8ea56728621e)

**Comment by arcxingye** [comment]
我觉得你应该看清楚点，我的是arcxingye，不是avcxingye

**Comment by niangaonb** [comment]
> 我觉得你应该看清楚点，我的是arcxingye，不是avcxingye
非常抱歉！这是一场因我疏忽的误会。是我朋友复制错链接了，非常抱歉。感谢您腾出空余时间进行回答。
