### ISSUE TITLE
已经是打不开的模样了

### ISSUE THREAD

**Issue by Similarityoung** [arcxingye/arcxingye.github.io#7]
![Screenshot_20230823_011656_com huawei browser](https://github.com/arcxingye/arcxingye.github.io/assets/94664304/14d3490f-c84f-4091-a905-75c3ade6b93e)

**Comment by arcxingye** [comment]
这些破浏览器硬说我违规 我也没办法啊

**Comment by vic233333** [comment]
github托管的站点多多少少都会这样吧，换个浏览器就好了。
